spring.application.name=auth-service

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=auth_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=auth_app
spring.datasource.password=AuthApp2026!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

app.jwt.secret=changeMoiEnValeurTresLongueEtAleatoireEnProduction123456789
app.jwt.expirationMs=3600000
spring.data.redis.host=localhost
spring.data.redis.port=6379